# DFN model.Setups comparison

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import pybamm
import plotly.express as px
import plotly.graph_objects as go 
from plotly.subplots import make_subplots
import numpy as np

WARNING:2026-04-07 15:08:56,700:jax._src.xla_bridge:794: An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

## Single models

#### Chen2020 — NMC811 / Graphite

In [5]:
parameters_values = pybamm.ParameterValues("Chen2020")
model = pybamm.lithium_ion.DFN()

In [6]:
experiment = pybamm.Experiment(
    [
        (
            "Discharge at 1C until 3V",
            "Rest for 1 hour",
            "Charge at 1C until 4.2V",
            "Hold at 4.2V until C/50",
        )
    ]
)
sim = pybamm.Simulation(model, 
                        experiment=experiment, 
                        parameter_values=parameters_values)
sol = sim.solve()

In [7]:
sol.plot()

interactive(children=(FloatSlider(value=0.0, description='t', max=3.784535198402846, step=0.03784535198402846)…

In [8]:
vars_to_export = ["Time [s]", "Terminal voltage [V]", "Current [A]"]
data = sol.get_data_dict(vars_to_export)

df = pd.DataFrame(data)
print(df.head())

   Time [s]  Terminal voltage [V]  Current [A]  Cycle  Step
0  0.000000              4.037727          5.0    0.0   0.0
1  0.007015              4.037689          5.0    0.0   0.0
2  0.014031              4.037651          5.0    0.0   0.0
3  0.028061              4.037575          5.0    0.0   0.0
4  0.056123              4.037424          5.0    0.0   0.0

In [9]:
df.to_csv("Chen2020.csv", index=False)

### OKane2022 — NMC / Graphite

In [2]:
parameters_values = pybamm.ParameterValues("OKane2022")
model = pybamm.lithium_ion.DFN()

In [10]:
experiment = pybamm.Experiment(
    [
        (
            "Discharge at 1C until 3V",
            "Rest for 1 hour",
            "Charge at 1C until 4.2V",
            "Hold at 4.2V until C/50",
        )
    ]
)
sim = pybamm.Simulation(model, 
                        experiment=experiment, 
                        parameter_values=parameters_values)
sol = sim.solve()

In [12]:
sol.plot()

interactive(children=(FloatSlider(value=0.0, description='t', max=3.784535198402846, step=0.03784535198402846)…

In [13]:
vars_to_export = ["Time [s]", "Terminal voltage [V]", "Current [A]"]
data = sol.get_data_dict(vars_to_export)

df = pd.DataFrame(data)
print(df.head())

   Time [s]  Terminal voltage [V]  Current [A]  Cycle  Step
0  0.000000              4.037727          5.0    0.0   0.0
1  0.007015              4.037689          5.0    0.0   0.0
2  0.014031              4.037651          5.0    0.0   0.0
3  0.028061              4.037575          5.0    0.0   0.0
4  0.056123              4.037424          5.0    0.0   0.0

In [14]:
df.to_csv("OKane2022.csv", index=False)

### Prada2013 — NCA / Graphite

In [15]:
parameters_values = pybamm.ParameterValues("Prada2013")
model = pybamm.lithium_ion.DFN()

In [16]:
experiment = pybamm.Experiment(
    [
        (
            "Discharge at 1C until 3V",
            "Rest for 1 hour",
            "Charge at 1C until 4.2V",
            "Hold at 4.2V until C/50",
        )
    ]
)
sim = pybamm.Simulation(model, 
                        experiment=experiment, 
                        parameter_values=parameters_values)
sol = sim.solve()

In [17]:
sol.plot()

interactive(children=(FloatSlider(value=0.0, description='t', max=2.4520225890827936, step=0.02452022589082793…

In [18]:
vars_to_export = ["Time [s]", "Terminal voltage [V]", "Current [A]"]
data = sol.get_data_dict(vars_to_export)

df = pd.DataFrame(data)
print(df.head())

   Time [s]  Terminal voltage [V]  Current [A]  Cycle  Step
0  0.000000              3.513929          2.3    0.0   0.0
1  0.001451              3.513804          2.3    0.0   0.0
2  0.002501              3.513714          2.3    0.0   0.0
3  0.004599              3.513535          2.3    0.0   0.0
4  0.008797              3.513179          2.3    0.0   0.0

In [19]:
df.to_csv("Prada2013.csv", index=False)

### ORegan2022 — Graphite-based Li-ion dataset

In [20]:
parameters_values = pybamm.ParameterValues("ORegan2022")
model = pybamm.lithium_ion.DFN()

In [21]:
experiment = pybamm.Experiment(
    [
        (
            "Discharge at 1C until 3V",
            "Rest for 1 hour",
            "Charge at 1C until 4.2V",
            "Hold at 4.2V until C/50",
        )
    ]
)
sim = pybamm.Simulation(model, 
                        experiment=experiment, 
                        parameter_values=parameters_values)
sol = sim.solve()

In [22]:
sol.plot()

interactive(children=(FloatSlider(value=0.0, description='t', max=2.0498512360462864, step=0.02049851236046286…

In [23]:
vars_to_export = ["Time [s]", "Terminal voltage [V]", "Current [A]"]
data = sol.get_data_dict(vars_to_export)

df = pd.DataFrame(data)
print(df.head())

   Time [s]  Terminal voltage [V]  Current [A]  Cycle  Step
0  0.000000              4.112825          5.0    0.0   0.0
1  0.006917              4.112765          5.0    0.0   0.0
2  0.013834              4.112705          5.0    0.0   0.0
3  0.027669              4.112586          5.0    0.0   0.0
4  0.055338              4.112349          5.0    0.0   0.0

In [24]:
df.to_csv("ORegan2022.csv", index=False)

### Chayambuka2022 — Solid-state related dataset

In [25]:
parameters_values = pybamm.ParameterValues("Chayambuka2022")
model = pybamm.lithium_ion.DFN()

In [26]:
experiment = pybamm.Experiment(
    [
        (
            "Discharge at 1C until 3V",
            "Rest for 1 hour",
            "Charge at 1C until 4.2V",
            "Hold at 4.2V until C/50",
        )
    ]
)
sim = pybamm.Simulation(model, 
                        experiment=experiment, 
                        parameter_values=parameters_values)
sol = sim.solve()

In [27]:
sol.plot()

interactive(children=(FloatSlider(value=0.0, description='t', max=9.540594454251545, step=0.09540594454251546)…

In [28]:
vars_to_export = ["Time [s]", "Terminal voltage [V]", "Current [A]"]
data = sol.get_data_dict(vars_to_export)

df = pd.DataFrame(data)
print(df.head())

   Time [s]  Terminal voltage [V]  Current [A]  Cycle  Step
0  0.000000              3.821293        0.003    0.0   0.0
1  0.041797              3.820931        0.003    0.0   0.0
2  0.083594              3.820606        0.003    0.0   0.0
3  0.167188              3.820028        0.003    0.0   0.0
4  0.317656              3.819191        0.003    0.0   0.0

In [29]:
df.to_csv("Chayambuka2022.csv", index=False)

## Parametries comparison

In [2]:
presets = {
    "Chen2020":       pybamm.ParameterValues("Chen2020"),
    "OKane2022":      pybamm.ParameterValues("OKane2022"),
    "Chayambuka2022": pybamm.ParameterValues("Chayambuka2022"),
    "ORegan2022":     pybamm.ParameterValues("ORegan2022"),
    "Prada2013":      pybamm.ParameterValues("Prada2013"),
}

In [3]:
rows = {}
for preset_name, params in presets.items():
    for key, value in params.items():
        if isinstance(value, (int, float)):          # only numbers, no functions
            if key not in rows:
                rows[key] = {}
            rows[key][preset_name] = value

df_params = pd.DataFrame(rows).T
df_params.index.name = "Parameter"

df_params.to_csv("DFN_parameters_comparison.csv")
df_params

,Chen2020,OKane2022,Chayambuka2022,ORegan2022,Prada2013
Parameter,,,,,
Ideal gas constant [J.K-1.mol-1],8.314463e+00,8.314463e+00,8.314463e+00,8.314463e+00,8.314463e+00
Faraday constant [C.mol-1],9.648533e+04,9.648533e+04,9.648533e+04,9.648533e+04,9.648533e+04
Boltzmann constant [J.K-1],1.380649e-23,1.380649e-23,1.380649e-23,1.380649e-23,1.380649e-23
Electron charge [C],1.602177e-19,1.602177e-19,1.602177e-19,1.602177e-19,1.602177e-19
Ratio of lithium moles to SEI moles,2.000000e+00,1.000000e+00,NaN,NaN,NaN
...,...,...,...,...,...
Positive electrode LAM constant proportional term [s-1],NaN,2.777800e-07,NaN,NaN,NaN
Positive electrode LAM constant exponential term,NaN,2.000000e+00,NaN,NaN,NaN
Positive electrode critical stress [Pa],NaN,3.750000e+08,NaN,NaN,NaN
Separator Bruggeman coefficient (electrode),NaN,NaN,NaN,1.500000e+00,NaN
Electrolyte diffusivity [m2.s-1],NaN,NaN,NaN,NaN,2.000000e-10

In [4]:
df_diff = df_params[df_params.nunique(axis=1) > 1]
print(f"Different parameters: {len(df_diff)}")
df_diff

Different parameters: 41

,Chen2020,OKane2022,Chayambuka2022,ORegan2022,Prada2013
Parameter,,,,,
Ratio of lithium moles to SEI moles,2.000000e+00,1.000000,NaN,NaN,NaN
SEI growth activation energy [J.mol-1],0.000000e+00,38000.000000,NaN,NaN,NaN
Negative electrode thickness [m],8.520000e-05,0.000085,6.400000e-05,0.000085,3.400000e-05
Separator thickness [m],1.200000e-05,0.000012,2.500000e-05,0.000012,2.500000e-05
Positive electrode thickness [m],7.560000e-05,0.000076,6.800000e-05,0.000076,8.000000e-05
Electrode height [m],6.500000e-02,0.065000,2.540000e-04,0.065000,6.000000e-01
Electrode width [m],1.580000e+00,1.580000,1.000000e+00,1.580000,3.000000e-01
Negative current collector density [kg.m-3],8.960000e+03,8960.000000,NaN,8933.000000,NaN
Positive current collector density [kg.m-3],2.700000e+03,2700.000000,NaN,2702.000000,NaN
Nominal cell capacity [A.h],5.000000e+00,5.000000,3.000000e-03,5.000000,2.300000e+00
Current function [A],5.000000e+00,5.000000,3.000000e-03,5.000000,2.300000e+00
Negative electrode conductivity [S.m-1],2.150000e+02,215.000000,2.560000e+02,215.000000,2.150000e+02
Maximum concentration in negative electrode [mol.m-3],3.313300e+04,33133.000000,1.454000e+04,29583.000000,3.055500e+04
Negative particle diffusivity [m2.s-1],3.300000e-14,NaN,NaN,NaN,3.000000e-15
Negative electrode porosity,2.500000e-01,0.250000,5.100000e-01,0.250000,3.600000e-01
Negative electrode active material volume fraction,7.500000e-01,0.750000,4.890000e-01,0.750000,5.800000e-01
Negative particle radius [m],5.860000e-06,0.000006,3.480000e-06,0.000006,5.000000e-06
Negative electrode Bruggeman coefficient (electrode),0.000000e+00,1.500000,0.000000e+00,0.000000,1.500000e+00
Negative electrode density [kg.m-3],1.657000e+03,1657.000000,NaN,2060.000000,NaN
Positive electrode conductivity [S.m-1],1.800000e-01,0.180000,5.000000e+01,NaN,3.379507e-01
Maximum concentration in positive electrode [mol.m-3],6.310400e+04,63104.000000,1.532000e+04,51765.000000,2.280600e+04
Positive particle diffusivity [m2.s-1],4.000000e-15,NaN,NaN,NaN,5.900000e-18
Positive electrode porosity,3.350000e-01,0.335000,2.300000e-01,0.335000,4.260000e-01
Positive electrode active material volume fraction,6.650000e-01,0.665000,5.500000e-01,0.665000,3.740000e-01
Positive particle radius [m],5.220000e-06,0.000005,5.900000e-07,0.000005,5.000000e-08
Positive electrode Bruggeman coefficient (electrode),0.000000e+00,1.500000,0.000000e+00,0.000000,1.500000e+00
Positive electrode density [kg.m-3],3.262000e+03,3262.000000,NaN,3699.000000,NaN
Separator porosity,4.700000e-01,0.470000,5.500000e-01,0.470000,4.500000e-01
Separator density [kg.m-3],3.970000e+02,397.000000,NaN,1548.000000,NaN
Separator thermal conductivity [W.m-1.K-1],1.600000e-01,0.160000,NaN,0.334400,NaN
Initial concentration in electrolyte [mol.m-3],1.000000e+03,1000.000000,1.000000e+03,1000.000000,1.200000e+03
Cation transference number,2.594000e-01,0.259400,4.500000e-01,NaN,3.600000e-01
Reference temperature [K],2.981500e+02,298.150000,2.981500e+02,298.150000,2.980000e+02
Ambient temperature [K],2.981500e+02,298.150000,2.981500e+02,298.150000,2.980000e+02
Lower voltage cut-off [V],2.500000e+00,2.500000,2.000000e+00,2.500000,2.000000e+00
Upper voltage cut-off [V],4.200000e+00,4.200000,4.200000e+00,4.400000,3.600000e+00
Open-circuit voltage at 0% SOC [V],2.500000e+00,2.500000,2.000000e+00,2.500000,2.000000e+00
Open-circuit voltage at 100% SOC [V],4.200000e+00,4.200000,4.200000e+00,4.400000,3.600000e+00
Initial concentration in negative electrode [mol.m-3],2.986600e+04,29866.000000,1.352000e+04,28866.000000,2.474955e+04
Initial concentration in positive electrode [mol.m-3],1.703800e+04,17038.000000,3.320000e+03,13975.000000,8.666280e+01
Initial temperature [K],2.981500e+02,298.150000,2.981500e+02,298.150000,2.980000e+02

In [5]:
df_norm = df_diff.copy()
df_norm = df_norm.apply(lambda row: (row - row.min()) / (row.max() - row.min() + 1e-30), axis=1)

fig = px.imshow(
    df_norm,
    labels=dict(x="Preset", y="Parameter", color="Norm. value"),
    title="Parameter comparison across PyBaMM presets (normalized)",
    aspect="auto",
    color_continuous_scale="RdYlGn",
    template="plotly_dark",
)
fig.update_layout(height=900)
fig.show()

In [6]:
baseline = "Chen2020"
df_pct = df_diff.copy()

for col in df_pct.columns:
    if col != baseline:
        df_pct[col] = ((df_pct[col] - df_pct[baseline]) / df_pct[baseline].abs() * 100).round(1)

df_pct[baseline] = df_diff[baseline]   # оставляем исходные значения базы
df_pct.columns = [f"{c} (% vs Chen2020)" if c != baseline else f"{baseline} (base)" 
                  for c in df_pct.columns]
df_pct

,Chen2020 (base),OKane2022 (% vs Chen2020),Chayambuka2022 (% vs Chen2020),ORegan2022 (% vs Chen2020),Prada2013 (% vs Chen2020)
Parameter,,,,,
Ratio of lithium moles to SEI moles,2.000000e+00,-50.0,NaN,NaN,NaN
SEI growth activation energy [J.mol-1],0.000000e+00,inf,NaN,NaN,NaN
Negative electrode thickness [m],8.520000e-05,0.0,-24.9,0.0,-60.1
Separator thickness [m],1.200000e-05,0.0,108.3,0.0,108.3
Positive electrode thickness [m],7.560000e-05,0.0,-10.1,0.0,5.8
Electrode height [m],6.500000e-02,0.0,-99.6,0.0,823.1
Electrode width [m],1.580000e+00,0.0,-36.7,0.0,-81.0
Negative current collector density [kg.m-3],8.960000e+03,0.0,NaN,-0.3,NaN
Positive current collector density [kg.m-3],2.700000e+03,0.0,NaN,0.1,NaN
Nominal cell capacity [A.h],5.000000e+00,0.0,-99.9,0.0,-54.0
Current function [A],5.000000e+00,0.0,-99.9,0.0,-54.0
Negative electrode conductivity [S.m-1],2.150000e+02,0.0,19.1,0.0,0.0
Maximum concentration in negative electrode [mol.m-3],3.313300e+04,0.0,-56.1,-10.7,-7.8
Negative particle diffusivity [m2.s-1],3.300000e-14,NaN,NaN,NaN,-90.9
Negative electrode porosity,2.500000e-01,0.0,104.0,0.0,44.0
Negative electrode active material volume fraction,7.500000e-01,0.0,-34.8,0.0,-22.7
Negative particle radius [m],5.860000e-06,0.0,-40.6,0.0,-14.7
Negative electrode Bruggeman coefficient (electrode),0.000000e+00,inf,NaN,NaN,inf
Negative electrode density [kg.m-3],1.657000e+03,0.0,NaN,24.3,NaN
Positive electrode conductivity [S.m-1],1.800000e-01,0.0,27677.8,NaN,87.8
Maximum concentration in positive electrode [mol.m-3],6.310400e+04,0.0,-75.7,-18.0,-63.9
Positive particle diffusivity [m2.s-1],4.000000e-15,NaN,NaN,NaN,-99.9
Positive electrode porosity,3.350000e-01,0.0,-31.3,0.0,27.2
Positive electrode active material volume fraction,6.650000e-01,0.0,-17.3,0.0,-43.8
Positive particle radius [m],5.220000e-06,0.0,-88.7,0.0,-99.0
Positive electrode Bruggeman coefficient (electrode),0.000000e+00,inf,NaN,NaN,inf
Positive electrode density [kg.m-3],3.262000e+03,0.0,NaN,13.4,NaN
Separator porosity,4.700000e-01,0.0,17.0,0.0,-4.3
Separator density [kg.m-3],3.970000e+02,0.0,NaN,289.9,NaN
Separator thermal conductivity [W.m-1.K-1],1.600000e-01,0.0,NaN,109.0,NaN
Initial concentration in electrolyte [mol.m-3],1.000000e+03,0.0,0.0,0.0,20.0
Cation transference number,2.594000e-01,0.0,73.5,NaN,38.8
Reference temperature [K],2.981500e+02,0.0,0.0,0.0,-0.1
Ambient temperature [K],2.981500e+02,0.0,0.0,0.0,-0.1
Lower voltage cut-off [V],2.500000e+00,0.0,-20.0,0.0,-20.0
Upper voltage cut-off [V],4.200000e+00,0.0,0.0,4.8,-14.3
Open-circuit voltage at 0% SOC [V],2.500000e+00,0.0,-20.0,0.0,-20.0
Open-circuit voltage at 100% SOC [V],4.200000e+00,0.0,0.0,4.8,-14.3
Initial concentration in negative electrode [mol.m-3],2.986600e+04,0.0,-54.7,-3.3,-17.1
Initial concentration in positive electrode [mol.m-3],1.703800e+04,0.0,-80.5,-18.0,-99.5
Initial temperature [K],2.981500e+02,0.0,0.0,0.0,-0.1

## Model comparison

In [2]:
dataframes = {
    "Chayambuka": pd.read_csv("Chayambuka2022.csv"),
    "Chen":       pd.read_csv("Chen2020.csv"),
    "OKane":      pd.read_csv("OKane2022.csv"),
    "Prada":      pd.read_csv("Prada2013.csv"),
    "ORegan":     pd.read_csv("ORegan2022.csv"),
}

In [ ]:
colors = ["#636EFA", "#EF553B", "#00CC96", "#AB63FA", "#FFA15A"]a

###  1. Voltage vs Time

In [4]:
fig1 = go.Figure()
for (name, df), color in zip(dataframes.items(), colors):
    fig1.add_trace(go.Scatter(
        x=df["Time [s]"], y=df["Terminal voltage [V]"],
        mode="lines", name=name, line=dict(color=color, width=1)
    ))
fig1.update_layout(
    title="Terminal Voltage vs Time",
    xaxis_title="Time [s]", yaxis_title="Terminal Voltage [V]",
    template="plotly_dark", hovermode="x unified"
)
fig1.show()

### 2. Current vs Time

In [5]:
fig2 = go.Figure()
for (name, df), color in zip(dataframes.items(), colors):
    fig2.add_trace(go.Scatter(
        x=df["Time [s]"], y=df["Current [A]"],
        mode="lines", name=name, line=dict(color=color, width=1)
    ))
fig2.update_layout(
    title="Current vs Time",
    xaxis_title="Time [s]", yaxis_title="Current [A]",
    template="plotly_dark", hovermode="x unified"
)
fig2.show()

### 3.  Number of points by cycles (coverage comparison)

In [7]:
fig4 = go.Figure()
for (name, df), color in zip(dataframes.items(), colors):
    cycle_counts = df.groupby("Cycle").size().reset_index(name="count")
    fig4.add_trace(go.Bar(
        x=cycle_counts["Cycle"], y=cycle_counts["count"],
        name=name, marker_color=color, opacity=0.8
    ))
fig4.update_layout(
    title="Data points per Cycle",
    xaxis_title="Cycle", yaxis_title="Number of points",
    barmode="group", template="plotly_dark"
)
fig4.show()

### 4. General 2×2 subplot

In [15]:
fig5 = make_subplots(
    rows=2, cols=2,
    subplot_titles=["Voltage vs Time", "Current vs Time", "Points per Cycle"],
    shared_xaxes=False
)
for (name, df), color in zip(dataframes.items(), colors):
    show = True  # легенда один раз
    fig5.add_trace(go.Scatter(x=df["Time [s]"], y=df["Terminal voltage [V]"],
        mode="lines", name=name, line=dict(color=color, width=1),
        legendgroup=name, showlegend=show), row=1, col=1)
    fig5.add_trace(go.Scatter(x=df["Time [s]"], y=df["Current [A]"],
        mode="lines", name=name, line=dict(color=color, width=1),
        legendgroup=name, showlegend=False), row=1, col=2)

    cycle_counts = df.groupby("Cycle").size().reset_index(name="count")
    fig5.add_trace(go.Bar(x=cycle_counts["Cycle"], y=cycle_counts["count"],
        name=name, marker_color=color, opacity=0.8,
        legendgroup=name, showlegend=False), row=2, col=1)

fig5.update_layout(
    title="Battery datasets — overview comparison",
    template="plotly_dark", height=800,
    barmode="group", hovermode="x unified"
)
fig5.show()